/*
 * VideIO API
 *
 * VideIO project API specification.
 *
 * The version of the OpenAPI document: 1.0.6
 * 
 * Generated by: https://openapi-generator.tech
 */

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace MyWideIO.API.Models.Enums
{
    /// <summary>
    /// Gets or Sets ProcessingProgressEnum
    /// </summary>
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum ProcessingProgressEnum
    {

        /// <summary>
        /// Enum MetadataRecordCreated for MetadataRecordCreated
        /// </summary>
        [EnumMember(Value = "MetadataRecordCreated")]
        MetadataRecordCreated = 1,

        /// <summary>
        /// Enum Uploading for Uploading
        /// </summary>
        [EnumMember(Value = "Uploading")]
        Uploading = 2,

        /// <summary>
        /// Enum Uploaded for Uploaded
        /// </summary>
        [EnumMember(Value = "Uploaded")]
        Uploaded = 3,

        /// <summary>
        /// Enum FailedToUpload for FailedToUpload
        /// </summary>
        [EnumMember(Value = "FailedToUpload")]
        FailedToUpload = 4,

        [EnumMember(Value = "FailedToProcess")]
        FailedToProcess = 5,

        /// <summary>
        /// Enum Processing for Processing
        /// </summary>
        [EnumMember(Value = "Processing")]
        Processing = 6,

        /// <summary>
        /// Enum Ready for Ready
        /// </summary>
        [EnumMember(Value = "Ready")]
        Ready = 7
    }
}
