/*
 * VideIO API
 *
 * VideIO project API specification.
 *
 * The version of the OpenAPI document: 1.0.6
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using WideIO.API.Converters;
using System.Text.Json.Serialization;

namespace MyWideIO.API.Models.Enums
{
    /// <summary>
    /// Gets or Sets ReactionEnum
    /// </summary>
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum ReactionEnum
    {

        /// <summary>
        /// Enum Positive for Positive
        /// </summary>
        [EnumMember(Value = "Positive")]
        Positive = 1,

        /// <summary>
        /// Enum Negative for Negative
        /// </summary>
        [EnumMember(Value = "Negative")]
        Negative = 2,

        /// <summary>
        /// Enum None for None
        /// </summary>
        [EnumMember(Value = "None")]
        None = 3
    }
}
