/*
 * VideIO API
 *
 * VideIO project API specification.
 *
 * The version of the OpenAPI document: 1.0.6
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using WideIO.API.Converters;

namespace MyWideIO.API.Models.Enums
{
    /// <summary>
    /// Gets or Sets SortingDirections
    /// </summary>
    [TypeConverter(typeof(CustomEnumConverter<SortingDirectionsEnum>))]
    [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum SortingDirectionsEnum
    {

        /// <summary>
        /// Enum AscendingEnum for Ascending
        /// </summary>
        [EnumMember(Value = "Ascending")]
        Ascending = 1,

        /// <summary>
        /// Enum DescendingEnum for Descending
        /// </summary>
        [EnumMember(Value = "Descending")]
        Descending = 2
    }
}
