/*
 * VideIO API
 *
 * VideIO project API specification.
 *
 * The version of the OpenAPI document: 1.0.6
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using WideIO.API.Converters;
using System.Text.Json.Serialization;

namespace MyWideIO.API.Models.Enums
{
    /// <summary>
    /// Gets or Sets SortingTypes
    /// </summary>
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum SortingTypesEnum
    {

        /// <summary>
        /// Enum PublishDateEnum for PublishDate
        /// </summary>
        [EnumMember(Value = "PublishDate")]
        PublishDate = 1,

        /// <summary>
        /// Enum AlphabeticalEnum for Alphabetical
        /// </summary>
        [EnumMember(Value = "Alphabetical")]
        Alphabetical = 2,

        /// <summary>
        /// Enum PopularityEnum for Popularity
        /// </summary>
        [EnumMember(Value = "Popularity")]
        Popularity = 3
    }
}
