/*
 * VideIO API
 *
 * VideIO project API specification.
 *
 * The version of the OpenAPI document: 1.0.6
 * 
 * Generated by: https://openapi-generator.tech
 */

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace MyWideIO.API.Models.Enums
{
    /// <summary>
    /// Gets or Sets ProcessingProgressEnum
    /// </summary>
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum TicketTargetTypeEnum
    {

        /// <summary>
        /// Enum MetadataRecordCreated for MetadataRecordCreated
        /// </summary>
        [EnumMember(Value = "Video")]
        Video = 1,

        /// <summary>
        /// Enum Uploading for Uploading
        /// </summary>
        [EnumMember(Value = "User")]
        User = 2,

        /// <summary>
        /// Enum Uploaded for Uploaded
        /// </summary>
        [EnumMember(Value = "Playlist")]
        Playlist = 3,

        /// <summary>
        /// Enum FailedToUpload for FailedToUpload
        /// </summary>
        [EnumMember(Value = "Comment")]
        Comment = 4,

        /// <summary>
        /// Enum Processing for Processing
        /// </summary>
        [EnumMember(Value = "CommentResponse")]
        CommentResponse = 5
    }
}
