/*
 * VideIO API
 *
 * VideIO project API specification.
 *
 * The version of the OpenAPI document: 1.0.6
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using WideIO.API.Converters;
using System.Text.Json.Serialization;

namespace MyWideIO.API.Models.Enums
{
    /// <summary>
    /// Gets or Sets VisibilityEnum
    /// </summary>
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum VisibilityEnum
    {

        /// <summary>
        /// Enum Private for Private
        /// </summary>
        [EnumMember(Value = "Private")]
        Private = 1,

        /// <summary>
        /// Enum Public for Public
        /// </summary>
        [EnumMember(Value = "Public")]
        Public = 2
    }
}
