/*
 * VideIO API
 *
 * VideIO project API specification.
 *
 * The version of the OpenAPI document: 1.0.6
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using WideIO.API.Converters;

namespace WideIO.API.Models
{
    /// <summary>
    /// Gets or Sets ProcessingProgressDto
    /// </summary>
    [TypeConverter(typeof(CustomEnumConverter<ProcessingProgressDto>))]
    [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum ProcessingProgressDto
    {

        /// <summary>
        /// Enum MetadataRecordCreatedEnum for MetadataRecordCreated
        /// </summary>
        [EnumMember(Value = "MetadataRecordCreated")]
        MetadataRecordCreated = 1,

        /// <summary>
        /// Enum UploadingEnum for Uploading
        /// </summary>
        [EnumMember(Value = "Uploading")]
        UploadingEnum = 2,

        /// <summary>
        /// Enum UploadedEnum for Uploaded
        /// </summary>
        [EnumMember(Value = "Uploaded")]
        UploadedEnum = 3,

        /// <summary>
        /// Enum FailedToUploadEnum for FailedToUpload
        /// </summary>
        [EnumMember(Value = "FailedToUpload")]
        FailedToUploadEnum = 4,

        /// <summary>
        /// Enum ProcessingEnum for Processing
        /// </summary>
        [EnumMember(Value = "Processing")]
        ProcessingEnum = 5,

        /// <summary>
        /// Enum ReadyEnum for Ready
        /// </summary>
        [EnumMember(Value = "Ready")]
        ReadyEnum = 6
    }
}
