/*
 * VideIO API
 *
 * VideIO project API specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using WideIO.API.Converters;

namespace WideIO.API.Models
{ 
        /// <summary>
        /// Gets or Sets ProcessingProgressDto
        /// </summary>
        [TypeConverter(typeof(CustomEnumConverter<ProcessingProgressDto>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum ProcessingProgressDto
        {
            
            /// <summary>
            /// Enum QueuedEnum for Queued
            /// </summary>
            [EnumMember(Value = "Queued")]
            QueuedEnum = 1,
            
            /// <summary>
            /// Enum ProcessingEnum for Processing
            /// </summary>
            [EnumMember(Value = "Processing")]
            ProcessingEnum = 2,
            
            /// <summary>
            /// Enum DoneEnum for Done
            /// </summary>
            [EnumMember(Value = "Done")]
            DoneEnum = 3
        }
}
