/*
 * VideIO API
 *
 * VideIO project API specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using WideIO.API.Converters;

namespace WideIO.API.Models
{ 
        /// <summary>
        /// Gets or Sets ReactionDto
        /// </summary>
        [TypeConverter(typeof(CustomEnumConverter<ReactionDto>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum ReactionDto
        {
            
            /// <summary>
            /// Enum PositiveEnum for Positive
            /// </summary>
            [EnumMember(Value = "Positive")]
            PositiveEnum = 1,
            
            /// <summary>
            /// Enum NegativeEnum for Negative
            /// </summary>
            [EnumMember(Value = "Negative")]
            NegativeEnum = 2
        }
}
