/*
 * VideIO API
 *
 * VideIO project API specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using WideIO.API.Converters;
using System.Text.Json.Serialization;

namespace WideIO.API.Models
{
    /// <summary>
    /// Gets or Sets UserTypeDto
    /// </summary>
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum UserTypeDto
    {

        /// <summary>
        /// Enum SimpleEnum for Simple
        /// </summary>
        [EnumMember(Value = "Viewer")]
        Viewer = 1,

        /// <summary>
        /// Enum CreatorEnum for Creator
        /// </summary>
        [EnumMember(Value = "Creator")]
        Creator = 2,

        /// <summary>
        /// Enum AdministratorEnum for Administrator
        /// </summary>
        [EnumMember(Value = "Administrator")]
        Administrator = 3
    }
}
