/*
 * VideIO API
 *
 * VideIO project API specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using WideIO.API.Converters;

namespace WideIO.API.Models
{ 
        /// <summary>
        /// Gets or Sets VisibilityDto
        /// </summary>
        [TypeConverter(typeof(CustomEnumConverter<VisibilityDto>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum VisibilityDto
        {
            
            /// <summary>
            /// Enum PrivateEnum for Private
            /// </summary>
            [EnumMember(Value = "Private")]
            PrivateEnum = 1,
            
            /// <summary>
            /// Enum PublicEnum for Public
            /// </summary>
            [EnumMember(Value = "Public")]
            PublicEnum = 2
        }
}
