/*
 * VideIO API
 *
 * VideIO project API specification.
 *
 * The version of the OpenAPI document: 1.0.6
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using WideIO.API.Converters;

namespace MyWideIO.API.Models.Dto_Models
{
    /// <summary>
    /// Gets or Sets TicketStatus
    /// </summary>
    [TypeConverter(typeof(CustomEnumConverter<TicketStatusEnum>))]
    [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
    public enum TicketStatusEnum
    {

        /// <summary>
        /// Enum SubmittedEnum for Submitted
        /// </summary>
        [EnumMember(Value = "Submitted")]
        Submitted = 1,

        /// <summary>
        /// Enum ResolvedEnum for Resolved
        /// </summary>
        [EnumMember(Value = "Resolved")]
        Resolved = 2
    }
}
