/*
 * VideIO API
 *
 * VideIO project API specification.
 *
 * The version of the OpenAPI document: 1.0.6
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using WideIO.API.Converters;
using MyWideIO.API.Models.Enums;

namespace MyWideIO.API.Models.Dto_Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class UserDto : IEquatable<UserDto>
    {
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        /// <example>&quot;123e4567-e89b-12d3-a456-426614174000&quot;</example>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        /// <example>&quot;john.doe@mail.com&quot;</example>
        [DataMember(Name = "email", EmitDefaultValue = false)]
        public string Email { get; set; }

        /// <summary>
        /// Gets or Sets Nickname
        /// </summary>
        /// <example>&quot;johnny123&quot;</example>
        [DataMember(Name = "nickname", EmitDefaultValue = false)]
        public string Nickname { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        /// <example>&quot;John&quot;</example>
        [DataMember(Name = "name", EmitDefaultValue = false)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Surname
        /// </summary>
        /// <example>&quot;Doe&quot;</example>
        [DataMember(Name = "surname", EmitDefaultValue = false)]
        public string Surname { get; set; }

        /// <summary>
        /// Gets or Sets AccountBalance
        /// </summary>
        [DataMember(Name = "accountBalance", EmitDefaultValue = true)]
        public decimal? AccountBalance { get; set; }

        /// <summary>
        /// Gets or Sets UserTypeEnum
        /// </summary>
        [DataMember(Name = "userType", EmitDefaultValue = true)]
        public UserTypeEnum UserType { get; set; }

        /// <summary>
        /// Gets or Sets AvatarImage
        /// </summary>
        /// <example>&quot;https://example.com/avatar/user-id&quot;</example>
        [DataMember(Name = "avatarImage", EmitDefaultValue = true)]
        public string? AvatarImage { get; set; }

        /// <summary>
        /// Gets or Sets SubscriptionsCount
        /// </summary>
        [DataMember(Name = "subscriptionsCount", EmitDefaultValue = true)]
        public int? SubscriptionsCount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class UserDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Nickname: ").Append(Nickname).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Surname: ").Append(Surname).Append("\n");
            sb.Append("  AccountBalance: ").Append(AccountBalance).Append("\n");
            sb.Append("  UserType: ").Append(UserType).Append("\n");
            sb.Append("  AvatarImage: ").Append(AvatarImage).Append("\n");
            sb.Append("  SubscriptionsCount: ").Append(SubscriptionsCount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((UserDto)obj);
        }

        /// <summary>
        /// Returns true if UserDto instances are equal
        /// </summary>
        /// <param name="other">Instance of UserDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UserDto other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    Id == other.Id ||
                    Id != null &&
                    Id.Equals(other.Id)
                ) &&
                (
                    Email == other.Email ||
                    Email != null &&
                    Email.Equals(other.Email)
                ) &&
                (
                    Nickname == other.Nickname ||
                    Nickname != null &&
                    Nickname.Equals(other.Nickname)
                ) &&
                (
                    Name == other.Name ||
                    Name != null &&
                    Name.Equals(other.Name)
                ) &&
                (
                    Surname == other.Surname ||
                    Surname != null &&
                    Surname.Equals(other.Surname)
                ) &&
                (
                    AccountBalance == other.AccountBalance ||
                    AccountBalance != null &&
                    AccountBalance.Equals(other.AccountBalance)
                ) &&
                (
                    UserType == other.UserType ||

                    UserType.Equals(other.UserType)
                ) &&
                (
                    AvatarImage == other.AvatarImage ||
                    AvatarImage != null &&
                    AvatarImage.Equals(other.AvatarImage)
                ) &&
                (
                    SubscriptionsCount == other.SubscriptionsCount ||
                    SubscriptionsCount != null &&
                    SubscriptionsCount.Equals(other.SubscriptionsCount)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (Id != null)
                    hashCode = hashCode * 59 + Id.GetHashCode();
                if (Email != null)
                    hashCode = hashCode * 59 + Email.GetHashCode();
                if (Nickname != null)
                    hashCode = hashCode * 59 + Nickname.GetHashCode();
                if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                if (Surname != null)
                    hashCode = hashCode * 59 + Surname.GetHashCode();
                if (AccountBalance != null)
                    hashCode = hashCode * 59 + AccountBalance.GetHashCode();

                hashCode = hashCode * 59 + UserType.GetHashCode();
                if (AvatarImage != null)
                    hashCode = hashCode * 59 + AvatarImage.GetHashCode();
                if (SubscriptionsCount != null)
                    hashCode = hashCode * 59 + SubscriptionsCount.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(UserDto left, UserDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(UserDto left, UserDto right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
