/*
 * VideIO API
 *
 * VideIO project API specification.
 *
 * The version of the OpenAPI document: 1.0.6
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using WideIO.API.Converters;
using MyWideIO.API.Models.Enums;

namespace MyWideIO.API.Models.Dto_Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class VideoReactionDto : IEquatable<VideoReactionDto>
    {
        /// <summary>
        /// Gets or Sets PositiveCount
        /// </summary>
        [DataMember(Name = "positiveCount", EmitDefaultValue = true)]
        public int PositiveCount { get; set; }

        /// <summary>
        /// Gets or Sets NegativeCount
        /// </summary>
        [DataMember(Name = "negativeCount", EmitDefaultValue = true)]
        public int NegativeCount { get; set; }

        /// <summary>
        /// Gets or Sets CurrentUserReaction
        /// </summary>
        [DataMember(Name = "currentUserReaction", EmitDefaultValue = true)]
        public ReactionEnum CurrentUserReaction { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class VideoReactionDto {\n");
            sb.Append("  PositiveCount: ").Append(PositiveCount).Append("\n");
            sb.Append("  NegativeCount: ").Append(NegativeCount).Append("\n");
            sb.Append("  CurrentUserReaction: ").Append(CurrentUserReaction).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((VideoReactionDto)obj);
        }

        /// <summary>
        /// Returns true if VideoReactionDto instances are equal
        /// </summary>
        /// <param name="other">Instance of VideoReactionDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VideoReactionDto other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    PositiveCount == other.PositiveCount ||

                    PositiveCount.Equals(other.PositiveCount)
                ) &&
                (
                    NegativeCount == other.NegativeCount ||

                    NegativeCount.Equals(other.NegativeCount)
                ) &&
                (
                    CurrentUserReaction == other.CurrentUserReaction ||

                    CurrentUserReaction.Equals(other.CurrentUserReaction)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)

                hashCode = hashCode * 59 + PositiveCount.GetHashCode();

                hashCode = hashCode * 59 + NegativeCount.GetHashCode();

                hashCode = hashCode * 59 + CurrentUserReaction.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(VideoReactionDto left, VideoReactionDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(VideoReactionDto left, VideoReactionDto right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
