/*
 * VideIO API
 *
 * VideIO project API specification.
 *
 * The version of the OpenAPI document: 1.0.6
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using WideIO.API.Converters;
using MyWideIO.API.Models.Enums;

namespace MyWideIO.API.Models.Dto_Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class VideoMetadataDto : IEquatable<VideoMetadataDto>
    {
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        /// <example>&quot;123e4567-e89b-12d3-a456-426614174000&quot;</example>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public Guid Id { get; set; }

        /// <summary>
        /// Gets or Sets Title
        /// </summary>
        /// <example>&quot;How to wash dishes&quot;</example>
        [DataMember(Name = "title", EmitDefaultValue = false)]
        public string Title { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        /// <example>&quot;I&#39;ll teach you how to wash your dishes! All you need is a sponge and dishwashing soap&quot;</example>
        [DataMember(Name = "description", EmitDefaultValue = false)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets Thumbnail
        /// </summary>
        /// <example>&quot;https://example.com/thumbnail/video-id&quot;</example>
        [DataMember(Name = "thumbnail", EmitDefaultValue = false)]
        public string Thumbnail { get; set; }

        /// <summary>
        /// Gets or Sets AuthorId
        /// </summary>
        /// <example>&quot;123e4567-e89b-12d3-a456-426614174000&quot;</example>
        [DataMember(Name = "authorId", EmitDefaultValue = false)]
        public Guid AuthorId { get; set; }

        /// <summary>
        /// Gets or Sets AuthorNickname
        /// </summary>
        /// <example>&quot;john.doe123&quot;</example>
        [DataMember(Name = "authorNickname", EmitDefaultValue = false)]
        public string AuthorNickname { get; set; }

        /// <summary>
        /// Gets or Sets ViewCount
        /// </summary>
        /// <example>1234503</example>
        [DataMember(Name = "viewCount", EmitDefaultValue = true)]
        public int ViewCount { get; set; }

        /// <summary>
        /// Gets or Sets Tags
        /// </summary>
        [DataMember(Name = "tags", EmitDefaultValue = false)]
        public List<string> Tags { get; set; }

        /// <summary>
        /// Gets or Sets Visibility
        /// </summary>
        [DataMember(Name = "visibility", EmitDefaultValue = true)]
        public VisibilityEnum Visibility { get; set; }

        /// <summary>
        /// Gets or Sets ProcessingProgress
        /// </summary>
        [DataMember(Name = "processingProgress", EmitDefaultValue = true)]
        public ProcessingProgressEnum ProcessingProgress { get; set; }

        /// <summary>
        /// Gets or Sets UploadDate
        /// </summary>
        [DataMember(Name = "uploadDate", EmitDefaultValue = false)]
        public DateTime UploadDate { get; set; }

        /// <summary>
        /// Gets or Sets EditDate
        /// </summary>
        [DataMember(Name = "editDate", EmitDefaultValue = false)]
        public DateTime EditDate { get; set; }

        /// <summary>
        /// (hh:)mm:ss
        /// </summary>
        /// <value>(hh:)mm:ss</value>
        /// <example>&quot;743&quot;</example>
        [DataMember(Name = "duration", EmitDefaultValue = false)]
        public string? Duration { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class VideoMetadataDto {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  Thumbnail: ").Append(Thumbnail).Append("\n");
            sb.Append("  AuthorId: ").Append(AuthorId).Append("\n");
            sb.Append("  AuthorNickname: ").Append(AuthorNickname).Append("\n");
            sb.Append("  ViewCount: ").Append(ViewCount).Append("\n");
            sb.Append("  Tags: ").Append(Tags).Append("\n");
            sb.Append("  Visibility: ").Append(Visibility).Append("\n");
            sb.Append("  ProcessingProgress: ").Append(ProcessingProgress).Append("\n");
            sb.Append("  UploadDate: ").Append(UploadDate).Append("\n");
            sb.Append("  EditDate: ").Append(EditDate).Append("\n");
            sb.Append("  Duration: ").Append(Duration).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((VideoMetadataDto)obj);
        }

        /// <summary>
        /// Returns true if VideoMetadataDto instances are equal
        /// </summary>
        /// <param name="other">Instance of VideoMetadataDto to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VideoMetadataDto other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    Id == other.Id ||
                    Id != null &&
                    Id.Equals(other.Id)
                ) &&
                (
                    Title == other.Title ||
                    Title != null &&
                    Title.Equals(other.Title)
                ) &&
                (
                    Description == other.Description ||
                    Description != null &&
                    Description.Equals(other.Description)
                ) &&
                (
                    Thumbnail == other.Thumbnail ||
                    Thumbnail != null &&
                    Thumbnail.Equals(other.Thumbnail)
                ) &&
                (
                    AuthorId == other.AuthorId ||
                    AuthorId != null &&
                    AuthorId.Equals(other.AuthorId)
                ) &&
                (
                    AuthorNickname == other.AuthorNickname ||
                    AuthorNickname != null &&
                    AuthorNickname.Equals(other.AuthorNickname)
                ) &&
                (
                    ViewCount == other.ViewCount ||

                    ViewCount.Equals(other.ViewCount)
                ) &&
                (
                    Tags == other.Tags ||
                    Tags != null &&
                    other.Tags != null &&
                    Tags.SequenceEqual(other.Tags)
                ) &&
                (
                    Visibility == other.Visibility ||

                    Visibility.Equals(other.Visibility)
                ) &&
                (
                    ProcessingProgress == other.ProcessingProgress ||

                    ProcessingProgress.Equals(other.ProcessingProgress)
                ) &&
                (
                    UploadDate == other.UploadDate ||
                    UploadDate != null &&
                    UploadDate.Equals(other.UploadDate)
                ) &&
                (
                    EditDate == other.EditDate ||
                    EditDate != null &&
                    EditDate.Equals(other.EditDate)
                ) &&
                (
                    Duration == other.Duration ||
                    Duration != null &&
                    Duration.Equals(other.Duration)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                if (Id != null)
                    hashCode = hashCode * 59 + Id.GetHashCode();
                if (Title != null)
                    hashCode = hashCode * 59 + Title.GetHashCode();
                if (Description != null)
                    hashCode = hashCode * 59 + Description.GetHashCode();
                if (Thumbnail != null)
                    hashCode = hashCode * 59 + Thumbnail.GetHashCode();
                if (AuthorId != null)
                    hashCode = hashCode * 59 + AuthorId.GetHashCode();
                if (AuthorNickname != null)
                    hashCode = hashCode * 59 + AuthorNickname.GetHashCode();

                hashCode = hashCode * 59 + ViewCount.GetHashCode();
                if (Tags != null)
                    hashCode = hashCode * 59 + Tags.GetHashCode();

                hashCode = hashCode * 59 + Visibility.GetHashCode();

                hashCode = hashCode * 59 + ProcessingProgress.GetHashCode();
                if (UploadDate != null)
                    hashCode = hashCode * 59 + UploadDate.GetHashCode();
                if (EditDate != null)
                    hashCode = hashCode * 59 + EditDate.GetHashCode();
                if (Duration != null)
                    hashCode = hashCode * 59 + Duration.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
#pragma warning disable 1591

        public static bool operator ==(VideoMetadataDto left, VideoMetadataDto right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(VideoMetadataDto left, VideoMetadataDto right)
        {
            return !Equals(left, right);
        }

#pragma warning restore 1591
        #endregion Operators
    }
}
